// FAVORITES AND CART
export const CHECK_CART_HAS_ITEMS = 'CHECK_CART_HAS_ITEMS';
export const CHECK_FAVORITES_HAS_ITEMS = 'CHECK_FAVORITES_HAS_ITEMS';
export const ITEM_ADDED = 'ITEM_ADDED';

// SEARCH | ITEM FILTER, SORT
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECIEVE_ITEMS_SUCCESS = 'RECIEVE_ITEMS_SUCCESS';
export const RECIEVE_ITEMS_FAILURE = 'RECIEVE_ITEMS_FAILURE';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const UPDATE_GENDER = 'UPDATE_GENDER';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const CHANGE_SORT_BY = 'CHANGE_SORT_BY';
export const SET_ITEM_ARRAY_CHANGED_FALSE = 'SET_ITEM_ARRAY_CHANGED_FALSE';

// MODAL
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_HEADER_MODAL = 'OPEN_HEADER_MODAL';
export const OPEN_SEARCH_MODAL = 'OPEN_SEARCH_MODAL';