// FAVORITES AND CART
export const CHECK_CART_HAS_ITEMS = 'CHECK_CART_HAS_ITEMS';
export const CHECK_FAVORITES_HAS_ITEMS = 'CHECK_FAVORITES_HAS_ITEMS';
export const ITEM_ADDED = 'ITEM_ADDED';
export const CLOSE_MODEL = 'CLOSE_MODEL';
export const OPEN_MODEL = 'OPEN_MODEL';

// SEARCH | ITEM FILTER, SORT
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECIEVE_ITEMS_SUCCESS = 'RECIEVE_ITEMS_SUCCESS';
export const RECIEVE_ITEMS_FAILURE = 'RECIEVE_ITEMS_FAILURE';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
